数あてゲーム完成
Seagull-N/hello pull request #2
Opened 2022-06-20 01:29 UTC by Seagull-N

数あてゲームのチェック依頼

2022-06-20 01:44 UTC, muretti0114 commented
チェックしましたが，チャンスの回数が増えていくバグがあります．

```
チャンス：残り5回
２桁の正の整数を予想してください：
50
予想された値が正解の値より大きいです。
正解との差が20以上あります。
チャンス：残り6回
２桁の正の整数を予想してください：    
33
予想された値が正解の値より大きいです。
チャンス：残り7回
２桁の正の整数を予想してください：    
22
予想された値が正解の値より小さいです。
チャンス：残り8回
２桁の正の整数を予想してください：
10
予想された値が正解の値より小さいです。
チャンス：残り9回
２桁の正の整数を予想してください：
44
予想された値が正解の値より大きいです。
チャンス：残り10回
２桁の正の整数を予想してください：
33
予想された値が正解の値より大きいです。
チャンス：残り11回
２桁の正の整数を予想してください：
55
予想された値が正解の値より大きいです。
正解との差が20以上あります。
チャンス：残り12回
２桁の正の整数を予想してください：
66
予想された値が正解の値より大きいです。
正解との差が20以上あります。
チャンス：残り13回
２桁の正の整数を予想してください：
77
予想された値が正解の値より大きいです。
正解との差が20以上あります。
チャンス：残り14回
２桁の正の整数を予想してください：
33
予想された値が正解の値より大きいです。
チャンス：残り15回
２桁の正の整数を予想してください：
22
予想された値が正解の値より小さいです。
チャンス：残り16回
２桁の正の整数を予想してください：
12
予想された値が正解の値より小さいです。
チャンス：残り17回
２桁の正の整数を予想してください：
27
正解です。
```

2022-06-20 01:44 UTC, muretti0114 commented
修正のうえ，再提出してください．

2022-06-20 01:45 UTC, muretti0114 requested changes

2022-06-20 01:45 UTC, muretti0114 commented on kazuate/kazuate.java
> +        for (int i = 5; i > 0; i++) {
i-- ですな．

2022-06-21 01:45 UTC, muretti0114 approved these changes
チェックOKです．もう一人のメンバーにも査読してもらってから，マージしてください．

2022-06-21 06:49 UTC, Seagull-N commented
数あてゲーム完成

2022-06-21 06:49 UTC, merged